# Generated by Django 2.1.3 on 2018-12-03 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('distance', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
