# Generated by Django 2.1.3 on 2018-12-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_preffered',
            field=models.BooleanField(default=False),
        ),
    ]
