# Generated by Django 2.1.3 on 2018-12-05 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_is_preffered'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='store',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
