# Generated by Django 2.1.3 on 2018-12-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20181205_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(default='Not Specified', max_length=120),
        ),
        migrations.AddField(
            model_name='store',
            name='icon',
            field=models.CharField(default='Not Specified', max_length=400),
        ),
        migrations.AddField(
            model_name='store',
            name='vicinity',
            field=models.CharField(default='Not Specified', max_length=120),
        ),
    ]
